Project2/Project2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project2.Models;

namespace Project2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project2/Project2/Controllers/SpecialQueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Project2.Controllers
{
    public class SpecialQueryController : Controller
    {
        public IActionResult Index()
        {
			var BigList = from u in MyDB.Users
						  where u.PostList.Count != 0
						  select u.PostList;

			List<Models.Post> temp = new List<Models.Post>();
			foreach (List<Models.Post> lp in BigList.ToList())
				temp.AddRange(lp);

			return View(temp.OrderByDescending(p => p.CreatedAt).ToList());
        }
    }
}

Project2/Project2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Project2/Project2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Project2/Project2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<br />
<h1 class="text-center">Hello Binary Studio Academy 2018!</h1>
<br/>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height:200px">
            <h3 style="text-align:center">Query1</h3>
            <p>Получить количество комментов под постами конкретного пользователя (по айди) (список из пост-количество)</p>
            <a asp-controller="query1">
                <button class="btn btn-primary center-block" style="width:75px">
                    Go
                </button>
            </a>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height:200px">
            <h3 style="text-align:center">Query2</h3>
            <p>Получить список комментов под постами конкретного пользователя (по айди), где body коммента < 50 символов (список из комментов)</p>
            <a asp-controller="query2">
                <button class="btn btn-primary center-block" style="width:75px">
                    Go
                </button>
            </a>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height:200px">
            <h3 style="text-align:center">Query3</h3>
            <p>Получить список (id, name) из списка todos которые выполнены для конкретного пользователя (по айди)</p>
            <br />
            <a asp-controller="query3">
                <button class="btn btn-primary center-block" style="width:75px">
                    Go
                </button>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height:200px">
            <h3 style="text-align:center">Query4</h3>
            <p>Получить список пользователей по алфавиту (по возрастанию) с отсортированными todo items по длине name (по убыванию)</p>
            <a asp-controller="query4">
                <button class="btn btn-primary center-block" style="width:75px">
                    Go
                </button>
            </a>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height:200px">
            <h3 style="text-align:center">Query5</h3>
            <p style="text-align:center">Получить структуру UserInfo</p>
            <br />
            <br />
            <a asp-controller="query5">
            <button class="btn btn-primary center-block" style="width:75px">
                Go
            </button>
            </a>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="height:200px">
            <h3 style="text-align:center">Query6</h3>
            <p style="text-align:center">Получить структуру PostInfo</p>
            <br />
            <br />
            <a asp-controller="query6">
                <button class="btn btn-primary center-block" style="width:75px">
                    Go
                </button>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="thumbnail" >
            <h3 style="text-align:center">SpecialQuery</h3>
            <p style="text-align:center">Задача на креативность: создать страницу, где будут отображены все исходные данные в красивом виде, т.е. Пользователи с их постами и комментариями под ними, и тд.</p>
            <a asp-controller="SpecialQuery">
                <button class="btn btn-primary center-block" style="width:75px">
                    Go
                </button>
            </a>
        </div>
    </div>
</div>